/*
 * generated by Xtext 2.20.0
 */
package uk.ac.kcl.inf.cardgame;


/**
 * Use this class to register components to be used at runtime / without the Equinox extension registry.
 */
public class CardGameLanguageRuntimeModule extends AbstractCardGameLanguageRuntimeModule {
}
