/*
 * generated by Xtext 2.20.0
 */
package uk.ac.kcl.inf.cardgame.ide;


/**
 * Use this class to register ide components.
 */
public class CardGameLanguageIdeModule extends AbstractCardGameLanguageIdeModule {
}
