/*
 * generated by Xtext 2.20.0
 */
package uk.ac.kcl.inf.cardgame.ide;

import com.google.inject.Guice;
import com.google.inject.Injector;
import org.eclipse.xtext.util.Modules2;
import uk.ac.kcl.inf.cardgame.CardGameLanguageRuntimeModule;
import uk.ac.kcl.inf.cardgame.CardGameLanguageStandaloneSetup;

/**
 * Initialization support for running Xtext languages as language servers.
 */
public class CardGameLanguageIdeSetup extends CardGameLanguageStandaloneSetup {

	@Override
	public Injector createInjector() {
		return Guice.createInjector(Modules2.mixin(new CardGameLanguageRuntimeModule(), new CardGameLanguageIdeModule()));
	}
	
}
