/*
 * generated by Xtext 2.24.0
 */
package uk.ac.kcl.inf.cardgame.ui.tests;

import com.google.inject.Injector;
import org.eclipse.xtext.testing.IInjectorProvider;
import uk.ac.kcl.inf.cardgame.ui.internal.CardgameActivator;

public class CardGameLanguageUiInjectorProvider implements IInjectorProvider {

	@Override
	public Injector getInjector() {
		return CardgameActivator.getInstance().getInjector("uk.ac.kcl.inf.cardgame.CardGameLanguage");
	}

}
