/*
 * generated by Xtext 2.24.0
 */
package uk.ac.kcl.inf.cardgame.ui;

import com.google.inject.Injector;
import org.eclipse.xtext.ui.guice.AbstractGuiceAwareExecutableExtensionFactory;
import org.osgi.framework.Bundle;
import org.osgi.framework.FrameworkUtil;
import uk.ac.kcl.inf.cardgame.ui.internal.CardgameActivator;

/**
 * This class was generated. Customizations should only happen in a newly
 * introduced subclass. 
 */
public class CardGameLanguageExecutableExtensionFactory extends AbstractGuiceAwareExecutableExtensionFactory {

	@Override
	protected Bundle getBundle() {
		return FrameworkUtil.getBundle(CardgameActivator.class);
	}
	
	@Override
	protected Injector getInjector() {
		CardgameActivator activator = CardgameActivator.getInstance();
		return activator != null ? activator.getInjector(CardgameActivator.UK_AC_KCL_INF_CARDGAME_CARDGAMELANGUAGE) : null;
	}

}
