/*
 * generated by Xtext 2.20.0
 */
package uk.ac.kcl.inf.cardgame.ui;

import org.eclipse.ui.plugin.AbstractUIPlugin;

/**
 * Use this class to register components to be used within the Eclipse IDE.
 */
public class CardGameLanguageUiModule extends AbstractCardGameLanguageUiModule {

	public CardGameLanguageUiModule(AbstractUIPlugin plugin) {
		super(plugin);
	}
}
