/*
 * generated by Xtext 2.24.0
 */
package uk.ac.kcl.inf.cardgame.scoping;

import org.eclipse.xtext.scoping.impl.DelegatingScopeProvider;

public abstract class AbstractCardGameLanguageScopeProvider extends DelegatingScopeProvider {
}
