/**
 * generated by Xtext 2.24.0
 */
package uk.ac.kcl.inf.cardgame.cardGameLanguage;

import org.eclipse.emf.ecore.EAttribute;
import org.eclipse.emf.ecore.EClass;
import org.eclipse.emf.ecore.EEnum;
import org.eclipse.emf.ecore.EPackage;
import org.eclipse.emf.ecore.EReference;

/**
 * <!-- begin-user-doc -->
 * The <b>Package</b> for the model.
 * It contains accessors for the meta objects to represent
 * <ul>
 *   <li>each class,</li>
 *   <li>each feature of each class,</li>
 *   <li>each enum,</li>
 *   <li>and each data type</li>
 * </ul>
 * <!-- end-user-doc -->
 * @see uk.ac.kcl.inf.cardgame.cardGameLanguage.CardGameLanguageFactory
 * @model kind="package"
 * @generated
 */
public interface CardGameLanguagePackage extends EPackage
{
  /**
   * The package name.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  String eNAME = "cardGameLanguage";

  /**
   * The package namespace URI.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  String eNS_URI = "http://www.ac.uk/kcl/inf/cardgame/CardGameLanguage";

  /**
   * The package namespace name.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  String eNS_PREFIX = "cardGameLanguage";

  /**
   * The singleton instance of the package.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  CardGameLanguagePackage eINSTANCE = uk.ac.kcl.inf.cardgame.cardGameLanguage.impl.CardGameLanguagePackageImpl.init();

  /**
   * The meta object id for the '{@link uk.ac.kcl.inf.cardgame.cardGameLanguage.impl.CardGameImpl <em>Card Game</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see uk.ac.kcl.inf.cardgame.cardGameLanguage.impl.CardGameImpl
   * @see uk.ac.kcl.inf.cardgame.cardGameLanguage.impl.CardGameLanguagePackageImpl#getCardGame()
   * @generated
   */
  int CARD_GAME = 0;

  /**
   * The feature id for the '<em><b>Name</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int CARD_GAME__NAME = 0;

  /**
   * The feature id for the '<em><b>Cardpropertytypes</b></em>' containment reference list.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int CARD_GAME__CARDPROPERTYTYPES = 1;

  /**
   * The feature id for the '<em><b>Cards</b></em>' containment reference list.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int CARD_GAME__CARDS = 2;

  /**
   * The feature id for the '<em><b>Number</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int CARD_GAME__NUMBER = 3;

  /**
   * The feature id for the '<em><b>Rule</b></em>' containment reference list.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int CARD_GAME__RULE = 4;

  /**
   * The number of structural features of the '<em>Card Game</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int CARD_GAME_FEATURE_COUNT = 5;

  /**
   * The meta object id for the '{@link uk.ac.kcl.inf.cardgame.cardGameLanguage.impl.CardImpl <em>Card</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see uk.ac.kcl.inf.cardgame.cardGameLanguage.impl.CardImpl
   * @see uk.ac.kcl.inf.cardgame.cardGameLanguage.impl.CardGameLanguagePackageImpl#getCard()
   * @generated
   */
  int CARD = 1;

  /**
   * The feature id for the '<em><b>Name</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int CARD__NAME = 0;

  /**
   * The feature id for the '<em><b>Definition</b></em>' containment reference list.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int CARD__DEFINITION = 1;

  /**
   * The number of structural features of the '<em>Card</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int CARD_FEATURE_COUNT = 2;

  /**
   * The meta object id for the '{@link uk.ac.kcl.inf.cardgame.cardGameLanguage.impl.CardPropertyImpl <em>Card Property</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see uk.ac.kcl.inf.cardgame.cardGameLanguage.impl.CardPropertyImpl
   * @see uk.ac.kcl.inf.cardgame.cardGameLanguage.impl.CardGameLanguagePackageImpl#getCardProperty()
   * @generated
   */
  int CARD_PROPERTY = 2;

  /**
   * The feature id for the '<em><b>Type</b></em>' reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int CARD_PROPERTY__TYPE = 0;

  /**
   * The feature id for the '<em><b>Value</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int CARD_PROPERTY__VALUE = 1;

  /**
   * The number of structural features of the '<em>Card Property</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int CARD_PROPERTY_FEATURE_COUNT = 2;

  /**
   * The meta object id for the '{@link uk.ac.kcl.inf.cardgame.cardGameLanguage.impl.CardPropertyTypeImpl <em>Card Property Type</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see uk.ac.kcl.inf.cardgame.cardGameLanguage.impl.CardPropertyTypeImpl
   * @see uk.ac.kcl.inf.cardgame.cardGameLanguage.impl.CardGameLanguagePackageImpl#getCardPropertyType()
   * @generated
   */
  int CARD_PROPERTY_TYPE = 3;

  /**
   * The feature id for the '<em><b>Name</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int CARD_PROPERTY_TYPE__NAME = 0;

  /**
   * The number of structural features of the '<em>Card Property Type</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int CARD_PROPERTY_TYPE_FEATURE_COUNT = 1;

  /**
   * The meta object id for the '{@link uk.ac.kcl.inf.cardgame.cardGameLanguage.impl.GameRuleImpl <em>Game Rule</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see uk.ac.kcl.inf.cardgame.cardGameLanguage.impl.GameRuleImpl
   * @see uk.ac.kcl.inf.cardgame.cardGameLanguage.impl.CardGameLanguagePackageImpl#getGameRule()
   * @generated
   */
  int GAME_RULE = 4;

  /**
   * The feature id for the '<em><b>Name</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int GAME_RULE__NAME = 0;

  /**
   * The feature id for the '<em><b>Item</b></em>' reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int GAME_RULE__ITEM = 1;

  /**
   * The feature id for the '<em><b>Level</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int GAME_RULE__LEVEL = 2;

  /**
   * The number of structural features of the '<em>Game Rule</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int GAME_RULE_FEATURE_COUNT = 3;

  /**
   * The meta object id for the '{@link uk.ac.kcl.inf.cardgame.cardGameLanguage.impl.SingleRuleImpl <em>Single Rule</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see uk.ac.kcl.inf.cardgame.cardGameLanguage.impl.SingleRuleImpl
   * @see uk.ac.kcl.inf.cardgame.cardGameLanguage.impl.CardGameLanguagePackageImpl#getSingleRule()
   * @generated
   */
  int SINGLE_RULE = 5;

  /**
   * The feature id for the '<em><b>Name</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int SINGLE_RULE__NAME = GAME_RULE__NAME;

  /**
   * The feature id for the '<em><b>Item</b></em>' reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int SINGLE_RULE__ITEM = GAME_RULE__ITEM;

  /**
   * The feature id for the '<em><b>Level</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int SINGLE_RULE__LEVEL = GAME_RULE__LEVEL;

  /**
   * The feature id for the '<em><b>Role1</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int SINGLE_RULE__ROLE1 = GAME_RULE_FEATURE_COUNT + 0;

  /**
   * The feature id for the '<em><b>Number1</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int SINGLE_RULE__NUMBER1 = GAME_RULE_FEATURE_COUNT + 1;

  /**
   * The feature id for the '<em><b>Keyword</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int SINGLE_RULE__KEYWORD = GAME_RULE_FEATURE_COUNT + 2;

  /**
   * The feature id for the '<em><b>Role2</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int SINGLE_RULE__ROLE2 = GAME_RULE_FEATURE_COUNT + 3;

  /**
   * The feature id for the '<em><b>Number2</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int SINGLE_RULE__NUMBER2 = GAME_RULE_FEATURE_COUNT + 4;

  /**
   * The number of structural features of the '<em>Single Rule</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int SINGLE_RULE_FEATURE_COUNT = GAME_RULE_FEATURE_COUNT + 5;

  /**
   * The meta object id for the '{@link uk.ac.kcl.inf.cardgame.cardGameLanguage.impl.EqualRuleImpl <em>Equal Rule</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see uk.ac.kcl.inf.cardgame.cardGameLanguage.impl.EqualRuleImpl
   * @see uk.ac.kcl.inf.cardgame.cardGameLanguage.impl.CardGameLanguagePackageImpl#getEqualRule()
   * @generated
   */
  int EQUAL_RULE = 6;

  /**
   * The feature id for the '<em><b>Name</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int EQUAL_RULE__NAME = GAME_RULE__NAME;

  /**
   * The feature id for the '<em><b>Item</b></em>' reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int EQUAL_RULE__ITEM = GAME_RULE__ITEM;

  /**
   * The feature id for the '<em><b>Level</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int EQUAL_RULE__LEVEL = GAME_RULE__LEVEL;

  /**
   * The feature id for the '<em><b>Number</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int EQUAL_RULE__NUMBER = GAME_RULE_FEATURE_COUNT + 0;

  /**
   * The number of structural features of the '<em>Equal Rule</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int EQUAL_RULE_FEATURE_COUNT = GAME_RULE_FEATURE_COUNT + 1;

  /**
   * The meta object id for the '{@link uk.ac.kcl.inf.cardgame.cardGameLanguage.ExpressionKeyword <em>Expression Keyword</em>}' enum.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see uk.ac.kcl.inf.cardgame.cardGameLanguage.ExpressionKeyword
   * @see uk.ac.kcl.inf.cardgame.cardGameLanguage.impl.CardGameLanguagePackageImpl#getExpressionKeyword()
   * @generated
   */
  int EXPRESSION_KEYWORD = 7;

  /**
   * The meta object id for the '{@link uk.ac.kcl.inf.cardgame.cardGameLanguage.PlayerRole <em>Player Role</em>}' enum.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see uk.ac.kcl.inf.cardgame.cardGameLanguage.PlayerRole
   * @see uk.ac.kcl.inf.cardgame.cardGameLanguage.impl.CardGameLanguagePackageImpl#getPlayerRole()
   * @generated
   */
  int PLAYER_ROLE = 8;


  /**
   * Returns the meta object for class '{@link uk.ac.kcl.inf.cardgame.cardGameLanguage.CardGame <em>Card Game</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Card Game</em>'.
   * @see uk.ac.kcl.inf.cardgame.cardGameLanguage.CardGame
   * @generated
   */
  EClass getCardGame();

  /**
   * Returns the meta object for the attribute '{@link uk.ac.kcl.inf.cardgame.cardGameLanguage.CardGame#getName <em>Name</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Name</em>'.
   * @see uk.ac.kcl.inf.cardgame.cardGameLanguage.CardGame#getName()
   * @see #getCardGame()
   * @generated
   */
  EAttribute getCardGame_Name();

  /**
   * Returns the meta object for the containment reference list '{@link uk.ac.kcl.inf.cardgame.cardGameLanguage.CardGame#getCardpropertytypes <em>Cardpropertytypes</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference list '<em>Cardpropertytypes</em>'.
   * @see uk.ac.kcl.inf.cardgame.cardGameLanguage.CardGame#getCardpropertytypes()
   * @see #getCardGame()
   * @generated
   */
  EReference getCardGame_Cardpropertytypes();

  /**
   * Returns the meta object for the containment reference list '{@link uk.ac.kcl.inf.cardgame.cardGameLanguage.CardGame#getCards <em>Cards</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference list '<em>Cards</em>'.
   * @see uk.ac.kcl.inf.cardgame.cardGameLanguage.CardGame#getCards()
   * @see #getCardGame()
   * @generated
   */
  EReference getCardGame_Cards();

  /**
   * Returns the meta object for the attribute '{@link uk.ac.kcl.inf.cardgame.cardGameLanguage.CardGame#getNumber <em>Number</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Number</em>'.
   * @see uk.ac.kcl.inf.cardgame.cardGameLanguage.CardGame#getNumber()
   * @see #getCardGame()
   * @generated
   */
  EAttribute getCardGame_Number();

  /**
   * Returns the meta object for the containment reference list '{@link uk.ac.kcl.inf.cardgame.cardGameLanguage.CardGame#getRule <em>Rule</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference list '<em>Rule</em>'.
   * @see uk.ac.kcl.inf.cardgame.cardGameLanguage.CardGame#getRule()
   * @see #getCardGame()
   * @generated
   */
  EReference getCardGame_Rule();

  /**
   * Returns the meta object for class '{@link uk.ac.kcl.inf.cardgame.cardGameLanguage.Card <em>Card</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Card</em>'.
   * @see uk.ac.kcl.inf.cardgame.cardGameLanguage.Card
   * @generated
   */
  EClass getCard();

  /**
   * Returns the meta object for the attribute '{@link uk.ac.kcl.inf.cardgame.cardGameLanguage.Card#getName <em>Name</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Name</em>'.
   * @see uk.ac.kcl.inf.cardgame.cardGameLanguage.Card#getName()
   * @see #getCard()
   * @generated
   */
  EAttribute getCard_Name();

  /**
   * Returns the meta object for the containment reference list '{@link uk.ac.kcl.inf.cardgame.cardGameLanguage.Card#getDefinition <em>Definition</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference list '<em>Definition</em>'.
   * @see uk.ac.kcl.inf.cardgame.cardGameLanguage.Card#getDefinition()
   * @see #getCard()
   * @generated
   */
  EReference getCard_Definition();

  /**
   * Returns the meta object for class '{@link uk.ac.kcl.inf.cardgame.cardGameLanguage.CardProperty <em>Card Property</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Card Property</em>'.
   * @see uk.ac.kcl.inf.cardgame.cardGameLanguage.CardProperty
   * @generated
   */
  EClass getCardProperty();

  /**
   * Returns the meta object for the reference '{@link uk.ac.kcl.inf.cardgame.cardGameLanguage.CardProperty#getType <em>Type</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the reference '<em>Type</em>'.
   * @see uk.ac.kcl.inf.cardgame.cardGameLanguage.CardProperty#getType()
   * @see #getCardProperty()
   * @generated
   */
  EReference getCardProperty_Type();

  /**
   * Returns the meta object for the attribute '{@link uk.ac.kcl.inf.cardgame.cardGameLanguage.CardProperty#getValue <em>Value</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Value</em>'.
   * @see uk.ac.kcl.inf.cardgame.cardGameLanguage.CardProperty#getValue()
   * @see #getCardProperty()
   * @generated
   */
  EAttribute getCardProperty_Value();

  /**
   * Returns the meta object for class '{@link uk.ac.kcl.inf.cardgame.cardGameLanguage.CardPropertyType <em>Card Property Type</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Card Property Type</em>'.
   * @see uk.ac.kcl.inf.cardgame.cardGameLanguage.CardPropertyType
   * @generated
   */
  EClass getCardPropertyType();

  /**
   * Returns the meta object for the attribute '{@link uk.ac.kcl.inf.cardgame.cardGameLanguage.CardPropertyType#getName <em>Name</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Name</em>'.
   * @see uk.ac.kcl.inf.cardgame.cardGameLanguage.CardPropertyType#getName()
   * @see #getCardPropertyType()
   * @generated
   */
  EAttribute getCardPropertyType_Name();

  /**
   * Returns the meta object for class '{@link uk.ac.kcl.inf.cardgame.cardGameLanguage.GameRule <em>Game Rule</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Game Rule</em>'.
   * @see uk.ac.kcl.inf.cardgame.cardGameLanguage.GameRule
   * @generated
   */
  EClass getGameRule();

  /**
   * Returns the meta object for the attribute '{@link uk.ac.kcl.inf.cardgame.cardGameLanguage.GameRule#getName <em>Name</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Name</em>'.
   * @see uk.ac.kcl.inf.cardgame.cardGameLanguage.GameRule#getName()
   * @see #getGameRule()
   * @generated
   */
  EAttribute getGameRule_Name();

  /**
   * Returns the meta object for the reference '{@link uk.ac.kcl.inf.cardgame.cardGameLanguage.GameRule#getItem <em>Item</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the reference '<em>Item</em>'.
   * @see uk.ac.kcl.inf.cardgame.cardGameLanguage.GameRule#getItem()
   * @see #getGameRule()
   * @generated
   */
  EReference getGameRule_Item();

  /**
   * Returns the meta object for the attribute '{@link uk.ac.kcl.inf.cardgame.cardGameLanguage.GameRule#getLevel <em>Level</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Level</em>'.
   * @see uk.ac.kcl.inf.cardgame.cardGameLanguage.GameRule#getLevel()
   * @see #getGameRule()
   * @generated
   */
  EAttribute getGameRule_Level();

  /**
   * Returns the meta object for class '{@link uk.ac.kcl.inf.cardgame.cardGameLanguage.SingleRule <em>Single Rule</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Single Rule</em>'.
   * @see uk.ac.kcl.inf.cardgame.cardGameLanguage.SingleRule
   * @generated
   */
  EClass getSingleRule();

  /**
   * Returns the meta object for the attribute '{@link uk.ac.kcl.inf.cardgame.cardGameLanguage.SingleRule#getRole1 <em>Role1</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Role1</em>'.
   * @see uk.ac.kcl.inf.cardgame.cardGameLanguage.SingleRule#getRole1()
   * @see #getSingleRule()
   * @generated
   */
  EAttribute getSingleRule_Role1();

  /**
   * Returns the meta object for the attribute '{@link uk.ac.kcl.inf.cardgame.cardGameLanguage.SingleRule#getNumber1 <em>Number1</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Number1</em>'.
   * @see uk.ac.kcl.inf.cardgame.cardGameLanguage.SingleRule#getNumber1()
   * @see #getSingleRule()
   * @generated
   */
  EAttribute getSingleRule_Number1();

  /**
   * Returns the meta object for the attribute '{@link uk.ac.kcl.inf.cardgame.cardGameLanguage.SingleRule#getKeyword <em>Keyword</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Keyword</em>'.
   * @see uk.ac.kcl.inf.cardgame.cardGameLanguage.SingleRule#getKeyword()
   * @see #getSingleRule()
   * @generated
   */
  EAttribute getSingleRule_Keyword();

  /**
   * Returns the meta object for the attribute '{@link uk.ac.kcl.inf.cardgame.cardGameLanguage.SingleRule#getRole2 <em>Role2</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Role2</em>'.
   * @see uk.ac.kcl.inf.cardgame.cardGameLanguage.SingleRule#getRole2()
   * @see #getSingleRule()
   * @generated
   */
  EAttribute getSingleRule_Role2();

  /**
   * Returns the meta object for the attribute '{@link uk.ac.kcl.inf.cardgame.cardGameLanguage.SingleRule#getNumber2 <em>Number2</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Number2</em>'.
   * @see uk.ac.kcl.inf.cardgame.cardGameLanguage.SingleRule#getNumber2()
   * @see #getSingleRule()
   * @generated
   */
  EAttribute getSingleRule_Number2();

  /**
   * Returns the meta object for class '{@link uk.ac.kcl.inf.cardgame.cardGameLanguage.EqualRule <em>Equal Rule</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Equal Rule</em>'.
   * @see uk.ac.kcl.inf.cardgame.cardGameLanguage.EqualRule
   * @generated
   */
  EClass getEqualRule();

  /**
   * Returns the meta object for the attribute '{@link uk.ac.kcl.inf.cardgame.cardGameLanguage.EqualRule#getNumber <em>Number</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Number</em>'.
   * @see uk.ac.kcl.inf.cardgame.cardGameLanguage.EqualRule#getNumber()
   * @see #getEqualRule()
   * @generated
   */
  EAttribute getEqualRule_Number();

  /**
   * Returns the meta object for enum '{@link uk.ac.kcl.inf.cardgame.cardGameLanguage.ExpressionKeyword <em>Expression Keyword</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for enum '<em>Expression Keyword</em>'.
   * @see uk.ac.kcl.inf.cardgame.cardGameLanguage.ExpressionKeyword
   * @generated
   */
  EEnum getExpressionKeyword();

  /**
   * Returns the meta object for enum '{@link uk.ac.kcl.inf.cardgame.cardGameLanguage.PlayerRole <em>Player Role</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for enum '<em>Player Role</em>'.
   * @see uk.ac.kcl.inf.cardgame.cardGameLanguage.PlayerRole
   * @generated
   */
  EEnum getPlayerRole();

  /**
   * Returns the factory that creates the instances of the model.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the factory that creates the instances of the model.
   * @generated
   */
  CardGameLanguageFactory getCardGameLanguageFactory();

  /**
   * <!-- begin-user-doc -->
   * Defines literals for the meta objects that represent
   * <ul>
   *   <li>each class,</li>
   *   <li>each feature of each class,</li>
   *   <li>each enum,</li>
   *   <li>and each data type</li>
   * </ul>
   * <!-- end-user-doc -->
   * @generated
   */
  interface Literals
  {
    /**
     * The meta object literal for the '{@link uk.ac.kcl.inf.cardgame.cardGameLanguage.impl.CardGameImpl <em>Card Game</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see uk.ac.kcl.inf.cardgame.cardGameLanguage.impl.CardGameImpl
     * @see uk.ac.kcl.inf.cardgame.cardGameLanguage.impl.CardGameLanguagePackageImpl#getCardGame()
     * @generated
     */
    EClass CARD_GAME = eINSTANCE.getCardGame();

    /**
     * The meta object literal for the '<em><b>Name</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute CARD_GAME__NAME = eINSTANCE.getCardGame_Name();

    /**
     * The meta object literal for the '<em><b>Cardpropertytypes</b></em>' containment reference list feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference CARD_GAME__CARDPROPERTYTYPES = eINSTANCE.getCardGame_Cardpropertytypes();

    /**
     * The meta object literal for the '<em><b>Cards</b></em>' containment reference list feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference CARD_GAME__CARDS = eINSTANCE.getCardGame_Cards();

    /**
     * The meta object literal for the '<em><b>Number</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute CARD_GAME__NUMBER = eINSTANCE.getCardGame_Number();

    /**
     * The meta object literal for the '<em><b>Rule</b></em>' containment reference list feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference CARD_GAME__RULE = eINSTANCE.getCardGame_Rule();

    /**
     * The meta object literal for the '{@link uk.ac.kcl.inf.cardgame.cardGameLanguage.impl.CardImpl <em>Card</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see uk.ac.kcl.inf.cardgame.cardGameLanguage.impl.CardImpl
     * @see uk.ac.kcl.inf.cardgame.cardGameLanguage.impl.CardGameLanguagePackageImpl#getCard()
     * @generated
     */
    EClass CARD = eINSTANCE.getCard();

    /**
     * The meta object literal for the '<em><b>Name</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute CARD__NAME = eINSTANCE.getCard_Name();

    /**
     * The meta object literal for the '<em><b>Definition</b></em>' containment reference list feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference CARD__DEFINITION = eINSTANCE.getCard_Definition();

    /**
     * The meta object literal for the '{@link uk.ac.kcl.inf.cardgame.cardGameLanguage.impl.CardPropertyImpl <em>Card Property</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see uk.ac.kcl.inf.cardgame.cardGameLanguage.impl.CardPropertyImpl
     * @see uk.ac.kcl.inf.cardgame.cardGameLanguage.impl.CardGameLanguagePackageImpl#getCardProperty()
     * @generated
     */
    EClass CARD_PROPERTY = eINSTANCE.getCardProperty();

    /**
     * The meta object literal for the '<em><b>Type</b></em>' reference feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference CARD_PROPERTY__TYPE = eINSTANCE.getCardProperty_Type();

    /**
     * The meta object literal for the '<em><b>Value</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute CARD_PROPERTY__VALUE = eINSTANCE.getCardProperty_Value();

    /**
     * The meta object literal for the '{@link uk.ac.kcl.inf.cardgame.cardGameLanguage.impl.CardPropertyTypeImpl <em>Card Property Type</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see uk.ac.kcl.inf.cardgame.cardGameLanguage.impl.CardPropertyTypeImpl
     * @see uk.ac.kcl.inf.cardgame.cardGameLanguage.impl.CardGameLanguagePackageImpl#getCardPropertyType()
     * @generated
     */
    EClass CARD_PROPERTY_TYPE = eINSTANCE.getCardPropertyType();

    /**
     * The meta object literal for the '<em><b>Name</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute CARD_PROPERTY_TYPE__NAME = eINSTANCE.getCardPropertyType_Name();

    /**
     * The meta object literal for the '{@link uk.ac.kcl.inf.cardgame.cardGameLanguage.impl.GameRuleImpl <em>Game Rule</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see uk.ac.kcl.inf.cardgame.cardGameLanguage.impl.GameRuleImpl
     * @see uk.ac.kcl.inf.cardgame.cardGameLanguage.impl.CardGameLanguagePackageImpl#getGameRule()
     * @generated
     */
    EClass GAME_RULE = eINSTANCE.getGameRule();

    /**
     * The meta object literal for the '<em><b>Name</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute GAME_RULE__NAME = eINSTANCE.getGameRule_Name();

    /**
     * The meta object literal for the '<em><b>Item</b></em>' reference feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference GAME_RULE__ITEM = eINSTANCE.getGameRule_Item();

    /**
     * The meta object literal for the '<em><b>Level</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute GAME_RULE__LEVEL = eINSTANCE.getGameRule_Level();

    /**
     * The meta object literal for the '{@link uk.ac.kcl.inf.cardgame.cardGameLanguage.impl.SingleRuleImpl <em>Single Rule</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see uk.ac.kcl.inf.cardgame.cardGameLanguage.impl.SingleRuleImpl
     * @see uk.ac.kcl.inf.cardgame.cardGameLanguage.impl.CardGameLanguagePackageImpl#getSingleRule()
     * @generated
     */
    EClass SINGLE_RULE = eINSTANCE.getSingleRule();

    /**
     * The meta object literal for the '<em><b>Role1</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute SINGLE_RULE__ROLE1 = eINSTANCE.getSingleRule_Role1();

    /**
     * The meta object literal for the '<em><b>Number1</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute SINGLE_RULE__NUMBER1 = eINSTANCE.getSingleRule_Number1();

    /**
     * The meta object literal for the '<em><b>Keyword</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute SINGLE_RULE__KEYWORD = eINSTANCE.getSingleRule_Keyword();

    /**
     * The meta object literal for the '<em><b>Role2</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute SINGLE_RULE__ROLE2 = eINSTANCE.getSingleRule_Role2();

    /**
     * The meta object literal for the '<em><b>Number2</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute SINGLE_RULE__NUMBER2 = eINSTANCE.getSingleRule_Number2();

    /**
     * The meta object literal for the '{@link uk.ac.kcl.inf.cardgame.cardGameLanguage.impl.EqualRuleImpl <em>Equal Rule</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see uk.ac.kcl.inf.cardgame.cardGameLanguage.impl.EqualRuleImpl
     * @see uk.ac.kcl.inf.cardgame.cardGameLanguage.impl.CardGameLanguagePackageImpl#getEqualRule()
     * @generated
     */
    EClass EQUAL_RULE = eINSTANCE.getEqualRule();

    /**
     * The meta object literal for the '<em><b>Number</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute EQUAL_RULE__NUMBER = eINSTANCE.getEqualRule_Number();

    /**
     * The meta object literal for the '{@link uk.ac.kcl.inf.cardgame.cardGameLanguage.ExpressionKeyword <em>Expression Keyword</em>}' enum.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see uk.ac.kcl.inf.cardgame.cardGameLanguage.ExpressionKeyword
     * @see uk.ac.kcl.inf.cardgame.cardGameLanguage.impl.CardGameLanguagePackageImpl#getExpressionKeyword()
     * @generated
     */
    EEnum EXPRESSION_KEYWORD = eINSTANCE.getExpressionKeyword();

    /**
     * The meta object literal for the '{@link uk.ac.kcl.inf.cardgame.cardGameLanguage.PlayerRole <em>Player Role</em>}' enum.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see uk.ac.kcl.inf.cardgame.cardGameLanguage.PlayerRole
     * @see uk.ac.kcl.inf.cardgame.cardGameLanguage.impl.CardGameLanguagePackageImpl#getPlayerRole()
     * @generated
     */
    EEnum PLAYER_ROLE = eINSTANCE.getPlayerRole();

  }

} //CardGameLanguagePackage
