/**
 * generated by Xtext 2.24.0
 */
package uk.ac.kcl.inf.cardgame.cardGameLanguage;

import java.util.Arrays;
import java.util.Collections;
import java.util.List;

import org.eclipse.emf.common.util.Enumerator;

/**
 * <!-- begin-user-doc -->
 * A representation of the literals of the enumeration '<em><b>Expression Keyword</b></em>',
 * and utility methods for working with them.
 * <!-- end-user-doc -->
 * @see uk.ac.kcl.inf.cardgame.cardGameLanguage.CardGameLanguagePackage#getExpressionKeyword()
 * @model
 * @generated
 */
public enum ExpressionKeyword implements Enumerator
{
  /**
   * The '<em><b>Is Bigger Than</b></em>' literal object.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #IS_BIGGER_THAN_VALUE
   * @generated
   * @ordered
   */
  IS_BIGGER_THAN(0, "isBiggerThan", "isBiggerThan"),

  /**
   * The '<em><b>Is Smaller Than</b></em>' literal object.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #IS_SMALLER_THAN_VALUE
   * @generated
   * @ordered
   */
  IS_SMALLER_THAN(1, "isSmallerThan", "isSmallerThan"),

  /**
   * The '<em><b>Is Equal To</b></em>' literal object.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #IS_EQUAL_TO_VALUE
   * @generated
   * @ordered
   */
  IS_EQUAL_TO(2, "isEqualTo", "isEqualTo");

  /**
   * The '<em><b>Is Bigger Than</b></em>' literal value.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #IS_BIGGER_THAN
   * @model name="isBiggerThan"
   * @generated
   * @ordered
   */
  public static final int IS_BIGGER_THAN_VALUE = 0;

  /**
   * The '<em><b>Is Smaller Than</b></em>' literal value.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #IS_SMALLER_THAN
   * @model name="isSmallerThan"
   * @generated
   * @ordered
   */
  public static final int IS_SMALLER_THAN_VALUE = 1;

  /**
   * The '<em><b>Is Equal To</b></em>' literal value.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #IS_EQUAL_TO
   * @model name="isEqualTo"
   * @generated
   * @ordered
   */
  public static final int IS_EQUAL_TO_VALUE = 2;

  /**
   * An array of all the '<em><b>Expression Keyword</b></em>' enumerators.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  private static final ExpressionKeyword[] VALUES_ARRAY =
    new ExpressionKeyword[]
    {
      IS_BIGGER_THAN,
      IS_SMALLER_THAN,
      IS_EQUAL_TO,
    };

  /**
   * A public read-only list of all the '<em><b>Expression Keyword</b></em>' enumerators.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public static final List<ExpressionKeyword> VALUES = Collections.unmodifiableList(Arrays.asList(VALUES_ARRAY));

  /**
   * Returns the '<em><b>Expression Keyword</b></em>' literal with the specified literal value.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param literal the literal.
   * @return the matching enumerator or <code>null</code>.
   * @generated
   */
  public static ExpressionKeyword get(String literal)
  {
    for (int i = 0; i < VALUES_ARRAY.length; ++i)
    {
      ExpressionKeyword result = VALUES_ARRAY[i];
      if (result.toString().equals(literal))
      {
        return result;
      }
    }
    return null;
  }

  /**
   * Returns the '<em><b>Expression Keyword</b></em>' literal with the specified name.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param name the name.
   * @return the matching enumerator or <code>null</code>.
   * @generated
   */
  public static ExpressionKeyword getByName(String name)
  {
    for (int i = 0; i < VALUES_ARRAY.length; ++i)
    {
      ExpressionKeyword result = VALUES_ARRAY[i];
      if (result.getName().equals(name))
      {
        return result;
      }
    }
    return null;
  }

  /**
   * Returns the '<em><b>Expression Keyword</b></em>' literal with the specified integer value.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the integer value.
   * @return the matching enumerator or <code>null</code>.
   * @generated
   */
  public static ExpressionKeyword get(int value)
  {
    switch (value)
    {
      case IS_BIGGER_THAN_VALUE: return IS_BIGGER_THAN;
      case IS_SMALLER_THAN_VALUE: return IS_SMALLER_THAN;
      case IS_EQUAL_TO_VALUE: return IS_EQUAL_TO;
    }
    return null;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  private final int value;

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  private final String name;

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  private final String literal;

  /**
   * Only this class can construct instances.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  private ExpressionKeyword(int value, String name, String literal)
  {
    this.value = value;
    this.name = name;
    this.literal = literal;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public int getValue()
  {
    return value;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public String getName()
  {
    return name;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public String getLiteral()
  {
    return literal;
  }

  /**
   * Returns the literal value of the enumerator, which is its string representation.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public String toString()
  {
    return literal;
  }
  
} //ExpressionKeyword
