/**
 * generated by Xtext 2.24.0
 */
package uk.ac.kcl.inf.cardgame.cardGameLanguage;


/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Single Rule</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link uk.ac.kcl.inf.cardgame.cardGameLanguage.SingleRule#getRole1 <em>Role1</em>}</li>
 *   <li>{@link uk.ac.kcl.inf.cardgame.cardGameLanguage.SingleRule#getNumber1 <em>Number1</em>}</li>
 *   <li>{@link uk.ac.kcl.inf.cardgame.cardGameLanguage.SingleRule#getKeyword <em>Keyword</em>}</li>
 *   <li>{@link uk.ac.kcl.inf.cardgame.cardGameLanguage.SingleRule#getRole2 <em>Role2</em>}</li>
 *   <li>{@link uk.ac.kcl.inf.cardgame.cardGameLanguage.SingleRule#getNumber2 <em>Number2</em>}</li>
 * </ul>
 *
 * @see uk.ac.kcl.inf.cardgame.cardGameLanguage.CardGameLanguagePackage#getSingleRule()
 * @model
 * @generated
 */
public interface SingleRule extends GameRule
{
  /**
   * Returns the value of the '<em><b>Role1</b></em>' attribute.
   * The literals are from the enumeration {@link uk.ac.kcl.inf.cardgame.cardGameLanguage.PlayerRole}.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Role1</em>' attribute.
   * @see uk.ac.kcl.inf.cardgame.cardGameLanguage.PlayerRole
   * @see #setRole1(PlayerRole)
   * @see uk.ac.kcl.inf.cardgame.cardGameLanguage.CardGameLanguagePackage#getSingleRule_Role1()
   * @model
   * @generated
   */
  PlayerRole getRole1();

  /**
   * Sets the value of the '{@link uk.ac.kcl.inf.cardgame.cardGameLanguage.SingleRule#getRole1 <em>Role1</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Role1</em>' attribute.
   * @see uk.ac.kcl.inf.cardgame.cardGameLanguage.PlayerRole
   * @see #getRole1()
   * @generated
   */
  void setRole1(PlayerRole value);

  /**
   * Returns the value of the '<em><b>Number1</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Number1</em>' attribute.
   * @see #setNumber1(int)
   * @see uk.ac.kcl.inf.cardgame.cardGameLanguage.CardGameLanguagePackage#getSingleRule_Number1()
   * @model
   * @generated
   */
  int getNumber1();

  /**
   * Sets the value of the '{@link uk.ac.kcl.inf.cardgame.cardGameLanguage.SingleRule#getNumber1 <em>Number1</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Number1</em>' attribute.
   * @see #getNumber1()
   * @generated
   */
  void setNumber1(int value);

  /**
   * Returns the value of the '<em><b>Keyword</b></em>' attribute.
   * The literals are from the enumeration {@link uk.ac.kcl.inf.cardgame.cardGameLanguage.ExpressionKeyword}.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Keyword</em>' attribute.
   * @see uk.ac.kcl.inf.cardgame.cardGameLanguage.ExpressionKeyword
   * @see #setKeyword(ExpressionKeyword)
   * @see uk.ac.kcl.inf.cardgame.cardGameLanguage.CardGameLanguagePackage#getSingleRule_Keyword()
   * @model
   * @generated
   */
  ExpressionKeyword getKeyword();

  /**
   * Sets the value of the '{@link uk.ac.kcl.inf.cardgame.cardGameLanguage.SingleRule#getKeyword <em>Keyword</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Keyword</em>' attribute.
   * @see uk.ac.kcl.inf.cardgame.cardGameLanguage.ExpressionKeyword
   * @see #getKeyword()
   * @generated
   */
  void setKeyword(ExpressionKeyword value);

  /**
   * Returns the value of the '<em><b>Role2</b></em>' attribute.
   * The literals are from the enumeration {@link uk.ac.kcl.inf.cardgame.cardGameLanguage.PlayerRole}.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Role2</em>' attribute.
   * @see uk.ac.kcl.inf.cardgame.cardGameLanguage.PlayerRole
   * @see #setRole2(PlayerRole)
   * @see uk.ac.kcl.inf.cardgame.cardGameLanguage.CardGameLanguagePackage#getSingleRule_Role2()
   * @model
   * @generated
   */
  PlayerRole getRole2();

  /**
   * Sets the value of the '{@link uk.ac.kcl.inf.cardgame.cardGameLanguage.SingleRule#getRole2 <em>Role2</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Role2</em>' attribute.
   * @see uk.ac.kcl.inf.cardgame.cardGameLanguage.PlayerRole
   * @see #getRole2()
   * @generated
   */
  void setRole2(PlayerRole value);

  /**
   * Returns the value of the '<em><b>Number2</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Number2</em>' attribute.
   * @see #setNumber2(int)
   * @see uk.ac.kcl.inf.cardgame.cardGameLanguage.CardGameLanguagePackage#getSingleRule_Number2()
   * @model
   * @generated
   */
  int getNumber2();

  /**
   * Sets the value of the '{@link uk.ac.kcl.inf.cardgame.cardGameLanguage.SingleRule#getNumber2 <em>Number2</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Number2</em>' attribute.
   * @see #getNumber2()
   * @generated
   */
  void setNumber2(int value);

} // SingleRule
