/**
 * generated by Xtext 2.24.0
 */
package uk.ac.kcl.inf.cardgame.cardGameLanguage.impl;

import org.eclipse.emf.common.notify.Notification;

import org.eclipse.emf.ecore.EClass;

import org.eclipse.emf.ecore.impl.ENotificationImpl;

import uk.ac.kcl.inf.cardgame.cardGameLanguage.CardGameLanguagePackage;
import uk.ac.kcl.inf.cardgame.cardGameLanguage.ExpressionKeyword;
import uk.ac.kcl.inf.cardgame.cardGameLanguage.PlayerRole;
import uk.ac.kcl.inf.cardgame.cardGameLanguage.SingleRule;

/**
 * <!-- begin-user-doc -->
 * An implementation of the model object '<em><b>Single Rule</b></em>'.
 * <!-- end-user-doc -->
 * <p>
 * The following features are implemented:
 * </p>
 * <ul>
 *   <li>{@link uk.ac.kcl.inf.cardgame.cardGameLanguage.impl.SingleRuleImpl#getRole1 <em>Role1</em>}</li>
 *   <li>{@link uk.ac.kcl.inf.cardgame.cardGameLanguage.impl.SingleRuleImpl#getNumber1 <em>Number1</em>}</li>
 *   <li>{@link uk.ac.kcl.inf.cardgame.cardGameLanguage.impl.SingleRuleImpl#getKeyword <em>Keyword</em>}</li>
 *   <li>{@link uk.ac.kcl.inf.cardgame.cardGameLanguage.impl.SingleRuleImpl#getRole2 <em>Role2</em>}</li>
 *   <li>{@link uk.ac.kcl.inf.cardgame.cardGameLanguage.impl.SingleRuleImpl#getNumber2 <em>Number2</em>}</li>
 * </ul>
 *
 * @generated
 */
public class SingleRuleImpl extends GameRuleImpl implements SingleRule
{
  /**
   * The default value of the '{@link #getRole1() <em>Role1</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getRole1()
   * @generated
   * @ordered
   */
  protected static final PlayerRole ROLE1_EDEFAULT = PlayerRole.PLAYER;

  /**
   * The cached value of the '{@link #getRole1() <em>Role1</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getRole1()
   * @generated
   * @ordered
   */
  protected PlayerRole role1 = ROLE1_EDEFAULT;

  /**
   * The default value of the '{@link #getNumber1() <em>Number1</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getNumber1()
   * @generated
   * @ordered
   */
  protected static final int NUMBER1_EDEFAULT = 0;

  /**
   * The cached value of the '{@link #getNumber1() <em>Number1</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getNumber1()
   * @generated
   * @ordered
   */
  protected int number1 = NUMBER1_EDEFAULT;

  /**
   * The default value of the '{@link #getKeyword() <em>Keyword</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getKeyword()
   * @generated
   * @ordered
   */
  protected static final ExpressionKeyword KEYWORD_EDEFAULT = ExpressionKeyword.IS_BIGGER_THAN;

  /**
   * The cached value of the '{@link #getKeyword() <em>Keyword</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getKeyword()
   * @generated
   * @ordered
   */
  protected ExpressionKeyword keyword = KEYWORD_EDEFAULT;

  /**
   * The default value of the '{@link #getRole2() <em>Role2</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getRole2()
   * @generated
   * @ordered
   */
  protected static final PlayerRole ROLE2_EDEFAULT = PlayerRole.PLAYER;

  /**
   * The cached value of the '{@link #getRole2() <em>Role2</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getRole2()
   * @generated
   * @ordered
   */
  protected PlayerRole role2 = ROLE2_EDEFAULT;

  /**
   * The default value of the '{@link #getNumber2() <em>Number2</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getNumber2()
   * @generated
   * @ordered
   */
  protected static final int NUMBER2_EDEFAULT = 0;

  /**
   * The cached value of the '{@link #getNumber2() <em>Number2</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getNumber2()
   * @generated
   * @ordered
   */
  protected int number2 = NUMBER2_EDEFAULT;

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  protected SingleRuleImpl()
  {
    super();
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  protected EClass eStaticClass()
  {
    return CardGameLanguagePackage.Literals.SINGLE_RULE;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public PlayerRole getRole1()
  {
    return role1;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public void setRole1(PlayerRole newRole1)
  {
    PlayerRole oldRole1 = role1;
    role1 = newRole1 == null ? ROLE1_EDEFAULT : newRole1;
    if (eNotificationRequired())
      eNotify(new ENotificationImpl(this, Notification.SET, CardGameLanguagePackage.SINGLE_RULE__ROLE1, oldRole1, role1));
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public int getNumber1()
  {
    return number1;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public void setNumber1(int newNumber1)
  {
    int oldNumber1 = number1;
    number1 = newNumber1;
    if (eNotificationRequired())
      eNotify(new ENotificationImpl(this, Notification.SET, CardGameLanguagePackage.SINGLE_RULE__NUMBER1, oldNumber1, number1));
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public ExpressionKeyword getKeyword()
  {
    return keyword;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public void setKeyword(ExpressionKeyword newKeyword)
  {
    ExpressionKeyword oldKeyword = keyword;
    keyword = newKeyword == null ? KEYWORD_EDEFAULT : newKeyword;
    if (eNotificationRequired())
      eNotify(new ENotificationImpl(this, Notification.SET, CardGameLanguagePackage.SINGLE_RULE__KEYWORD, oldKeyword, keyword));
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public PlayerRole getRole2()
  {
    return role2;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public void setRole2(PlayerRole newRole2)
  {
    PlayerRole oldRole2 = role2;
    role2 = newRole2 == null ? ROLE2_EDEFAULT : newRole2;
    if (eNotificationRequired())
      eNotify(new ENotificationImpl(this, Notification.SET, CardGameLanguagePackage.SINGLE_RULE__ROLE2, oldRole2, role2));
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public int getNumber2()
  {
    return number2;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public void setNumber2(int newNumber2)
  {
    int oldNumber2 = number2;
    number2 = newNumber2;
    if (eNotificationRequired())
      eNotify(new ENotificationImpl(this, Notification.SET, CardGameLanguagePackage.SINGLE_RULE__NUMBER2, oldNumber2, number2));
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public Object eGet(int featureID, boolean resolve, boolean coreType)
  {
    switch (featureID)
    {
      case CardGameLanguagePackage.SINGLE_RULE__ROLE1:
        return getRole1();
      case CardGameLanguagePackage.SINGLE_RULE__NUMBER1:
        return getNumber1();
      case CardGameLanguagePackage.SINGLE_RULE__KEYWORD:
        return getKeyword();
      case CardGameLanguagePackage.SINGLE_RULE__ROLE2:
        return getRole2();
      case CardGameLanguagePackage.SINGLE_RULE__NUMBER2:
        return getNumber2();
    }
    return super.eGet(featureID, resolve, coreType);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public void eSet(int featureID, Object newValue)
  {
    switch (featureID)
    {
      case CardGameLanguagePackage.SINGLE_RULE__ROLE1:
        setRole1((PlayerRole)newValue);
        return;
      case CardGameLanguagePackage.SINGLE_RULE__NUMBER1:
        setNumber1((Integer)newValue);
        return;
      case CardGameLanguagePackage.SINGLE_RULE__KEYWORD:
        setKeyword((ExpressionKeyword)newValue);
        return;
      case CardGameLanguagePackage.SINGLE_RULE__ROLE2:
        setRole2((PlayerRole)newValue);
        return;
      case CardGameLanguagePackage.SINGLE_RULE__NUMBER2:
        setNumber2((Integer)newValue);
        return;
    }
    super.eSet(featureID, newValue);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public void eUnset(int featureID)
  {
    switch (featureID)
    {
      case CardGameLanguagePackage.SINGLE_RULE__ROLE1:
        setRole1(ROLE1_EDEFAULT);
        return;
      case CardGameLanguagePackage.SINGLE_RULE__NUMBER1:
        setNumber1(NUMBER1_EDEFAULT);
        return;
      case CardGameLanguagePackage.SINGLE_RULE__KEYWORD:
        setKeyword(KEYWORD_EDEFAULT);
        return;
      case CardGameLanguagePackage.SINGLE_RULE__ROLE2:
        setRole2(ROLE2_EDEFAULT);
        return;
      case CardGameLanguagePackage.SINGLE_RULE__NUMBER2:
        setNumber2(NUMBER2_EDEFAULT);
        return;
    }
    super.eUnset(featureID);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public boolean eIsSet(int featureID)
  {
    switch (featureID)
    {
      case CardGameLanguagePackage.SINGLE_RULE__ROLE1:
        return role1 != ROLE1_EDEFAULT;
      case CardGameLanguagePackage.SINGLE_RULE__NUMBER1:
        return number1 != NUMBER1_EDEFAULT;
      case CardGameLanguagePackage.SINGLE_RULE__KEYWORD:
        return keyword != KEYWORD_EDEFAULT;
      case CardGameLanguagePackage.SINGLE_RULE__ROLE2:
        return role2 != ROLE2_EDEFAULT;
      case CardGameLanguagePackage.SINGLE_RULE__NUMBER2:
        return number2 != NUMBER2_EDEFAULT;
    }
    return super.eIsSet(featureID);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public String toString()
  {
    if (eIsProxy()) return super.toString();

    StringBuilder result = new StringBuilder(super.toString());
    result.append(" (role1: ");
    result.append(role1);
    result.append(", number1: ");
    result.append(number1);
    result.append(", keyword: ");
    result.append(keyword);
    result.append(", role2: ");
    result.append(role2);
    result.append(", number2: ");
    result.append(number2);
    result.append(')');
    return result.toString();
  }

} //SingleRuleImpl
