/**
 * generated by Xtext 2.20.0
 */
package uk.ac.kcl.inf.cardgame.ui.quickfix;

import org.eclipse.emf.ecore.EObject;
import org.eclipse.xtext.ui.editor.model.edit.IMultiModification;
import org.eclipse.xtext.ui.editor.quickfix.DefaultQuickfixProvider;
import org.eclipse.xtext.ui.editor.quickfix.Fix;
import org.eclipse.xtext.ui.editor.quickfix.IssueResolutionAcceptor;
import org.eclipse.xtext.validation.Issue;
import org.eclipse.xtext.xbase.lib.StringExtensions;
import uk.ac.kcl.inf.cardgame.cardGameLanguage.Card;
import uk.ac.kcl.inf.cardgame.cardGameLanguage.CardPropertyType;
import uk.ac.kcl.inf.cardgame.validation.CardGameLanguageValidator;

/**
 * Custom quickfixes.
 * See https://www.eclipse.org/Xtext/documentation/310_eclipse_support.html#quick-fixes
 */
@SuppressWarnings("all")
public class CardGameLanguageQuickfixProvider extends DefaultQuickfixProvider {
  @Fix(CardGameLanguageValidator.INVALID_PROPERTY_TYPE)
  public void lowerCaseProperty(final Issue issue, final IssueResolutionAcceptor acceptor) {
    final IMultiModification<EObject> _function = (EObject element) -> {
      final CardPropertyType decl = ((CardPropertyType) element);
      decl.setName(StringExtensions.toFirstLower(decl.getName()));
    };
    acceptor.<EObject>acceptMulti(issue, "Lowercase property name", "Change the property name to start with a lower-case character.", null, _function);
  }
  
  @Fix(CardGameLanguageValidator.INVALID_CARD_NAME1)
  public void capitalCardName(final Issue issue, final IssueResolutionAcceptor acceptor) {
    final IMultiModification<EObject> _function = (EObject element) -> {
      final Card decl = ((Card) element);
      decl.setName(StringExtensions.toFirstUpper(decl.getName()));
    };
    acceptor.<EObject>acceptMulti(issue, "Start with a capital", "Change the card name to start with a capital.", null, _function);
  }
}
